auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: xiongjunnan.github.io
url: http://xiongjunnan.github.io
feed: /atom.xml
author_info: <a href="http://xiongjunnan.github.io">酸酸菜</a>
